name: OurCraft CI
on:
  push:
    branches:
      master
  pull_request:
    branches:
      master

env:
  SPIGOT_BUILD_TYPE: spigot
  SPIGOT_BUILD_REV: latest

jobs:
  build:
    name: Build Spigot
    runs-on: ubuntu-latest
    env:
      SPIGOT_BUILD_PATH: BuildTools
      SPIGOT_BUILD_OUTPUT_PATH: Dist
    steps:
      - uses: actions/checkout@v2
      - uses: git submodule init && git submodule update
      - name: Prepare for work
        run: spigot-build-tools/prepare-env && spigot-build-tools/prepare-work
      - name: Run BuildTools
        run: spigot-build-tools/build
      - name: Determine version
        run: spigot-build-tools/get-artifact-version.py
      - name: Prepare artifact for publishing
        run: spigot-build-tools/prepare-artifact.py
      - name: Publish Spigot
        uses: actions/upload-artifact@v2
        with:
          name: spigot.jar
          path: Dist/spigot.jar
      - name: Clean-up leftovers
        run: rm -rf $SPIGOT_BUILD_PATH/ && rm -rf $SPIGOT_BUILD_OUTPUT_PATH/
  publish:
    name: Publish to Docker repository
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: spigot.jar
          path: docker-image/path/spigot.jar
    
