name: OurCraft CI
on:
  push:
    branches:
      master
  pull_request:
    branches:
      master

env:
  SPIGOT_BUILD_OUTPUT_NAME: craftbukkit
  SPIGOT_BUILD_REV: latest

jobs:
  build:
    name: Build Spigot and compile CraftBukkit
    runs-on: ubuntu-latest
    env:
      SPIGOT_BUILD_PATH: BuildTools
      SPIGOT_BUILD_OUTPUT_PATH: Dist
    steps:
      - uses: actions/checkout@v2
      - name: Prepare for work
        run: bin/prepare-env && bin/prepare-work
      - name: Run BuildTools
        run: bin/build
      - name: Determine version
        run: bin/get-artifact-version.py
      - name: Prepare artifact for publishing
        run: bin/prepare-artifact.py
      - name: Publish Spigot
        uses: actions/upload-artifact@v2
        with:
          name: craftbukkit.jar
          path: Dist/craftbukkit.jar
      - name: Clean-up leftovers
        run: rm -rf $SPIGOT_BUILD_PATH/ && rm -rf $SPIGOT_BUILD_OUTPUT_PATH/
  publish:
    name: Publish to Docker repository
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: craftbukkit.jar
          path: docker-image/path/craftbukkit.jar
    
